"""supplier settings json, part lookup fields

Revision ID: 8b83cf5df9a0
Revises: 0665023a53b9
Create Date: 2026-03-05 12:41:05.618800

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b83cf5df9a0'
down_revision: Union[str, Sequence[str], None] = '0665023a53b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rohs_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attributes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_breaks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('supplier_data_updated_at', sa.DateTime(), nullable=True))

    # Migrate api_key → settings JSON before dropping the column
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, api_key FROM suppliers WHERE api_key IS NOT NULL")).fetchall()
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.drop_column('api_key')
    for row in rows:
        conn.execute(
            sa.text("UPDATE suppliers SET settings = :s WHERE id = :id"),
            {"s": json.dumps({"api_key": row[1]}), "id": row[0]},
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('settings')

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('supplier_data_updated_at')
        batch_op.drop_column('price_breaks')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('attributes')
        batch_op.drop_column('rohs_status')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
