"""remove barcode field

Revision ID: c592fd952fe8
Revises: 81cd0ebd8e4d
Create Date: 2026-03-04 21:28:13.615618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c592fd952fe8'
down_revision: Union[str, Sequence[str], None] = '81cd0ebd8e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_barcode'), table_name='parts')
    op.drop_column('parts', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('barcode', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_parts_barcode'), 'parts', ['barcode'], unique=1)
    # ### end Alembic commands ###
