"""add supplier and supplier_pn

Revision ID: e9a4373f9cad
Revises: c592fd952fe8
Create Date: 2026-03-05 00:20:51.866373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a4373f9cad'
down_revision: Union[str, Sequence[str], None] = 'c592fd952fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('supplier', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('supplier_pn', sa.String(), nullable=True))
    op.create_index(op.f('ix_parts_supplier_pn'), 'parts', ['supplier_pn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_supplier_pn'), table_name='parts')
    op.drop_column('parts', 'supplier_pn')
    op.drop_column('parts', 'supplier')
    # ### end Alembic commands ###
